### PR TITLE
Fix a bug related to editing in a new game

### LINKED ISSUE #116: Fix a bug related to editing in a new game

### PR DESCRIPTION
**Pull request by Xczheng0105**
fixes #116

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/ParserUtil.java [hunk 1]
```diff
@@ -140,7 +140,7 @@ public static Game parseGame(String game) throws ParseException {
         if (!Game.isValidGameName(trimmedGame)) {
             throw new ParseException(Game.MESSAGE_CONSTRAINTS);
         }
-        return new Game(trimmedGame);
+        return new Game(trimmedGame, new Username("tbc"), new SkillLevel("tbc"), new Role("tbc"));
```
Comment (JJtan2002) [inline src/main/java/seedu/address/logic/parser/ParserUtil.java:143]: Adding these fields with "tbc" as the input can be confusing for users. The Game constructor could be overloaded to make these fields optional. When no input is given for these fields, the field can be omitted from being displayed on the UI.
